const config=window.MUSHTBA_SUPABASE||{};const client=config.url&&config.publishableKey?window.supabase.createClient(config.url,config.publishableKey):null;const $=s=>document.querySelector(s);let products=[];let selectedImages=[];let existingImages=[];let draggedId=null;
const money=n=>new Intl.NumberFormat("sv-SE").format(Number(n)||0)+" kr";const slugify=s=>String(s||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function formError(m=""){ $("#formError").textContent=m } function showLogin(){ $("#loginView").hidden=false;$("#adminView").hidden=true }
async function handleSession(){const{data:{user}}=await client.auth.getUser();if(!user)return showLogin();const{data:admin,error}=await client.from("admin_users").select("email").eq("email",user.email).maybeSingle();if(error||!admin){await client.auth.signOut();$("#loginError").textContent=error?"Could not verify admin access.":"This account does not have admin access.";return showLogin()}$("#adminEmail").textContent=user.email;$("#loginView").hidden=true;$("#adminView").hidden=false;await loadProducts()}
async function boot(){if(!client){$("#loginError").textContent="Supabase is not configured.";return}const{data:{session}}=await client.auth.getSession();session?handleSession():showLogin();client.auth.onAuthStateChange((_,s)=>s?handleSession():showLogin())}
async function loadProducts(){const{data,error}=await client.from("products").select("*").order("featured",{ascending:false}).order("created_at",{ascending:false});if(error){console.error(error);return}products=data||[];renderStats();renderProducts();renderHealth()}
function renderStats(){const low=products.filter(p=>p.stock>0&&p.stock<=5).length,out=products.filter(p=>p.stock<=0).length;$("#statProducts").textContent=products.length;$("#statActive").textContent=products.filter(p=>p.status==="Active").length;$("#statLow").textContent=low;$("#statOut").textContent=out}
function renderProducts(){const q=$("#catalogSearch").value.toLowerCase(),f=$("#catalogFilter").value;let list=products.filter(p=>(p.name+" "+p.brand+" "+(p.category||"")).toLowerCase().includes(q));if(f==="Active"||f==="Draft")list=list.filter(p=>p.status===f);if(f==="low")list=list.filter(p=>p.stock>0&&p.stock<=5);if(f==="out")list=list.filter(p=>p.stock<=0);$("#productList").innerHTML=list.map(p=>{const img=p.images?.[0]||"";return '<div class="row" draggable="true" data-id="'+p.id+'"><span class="drag">⠿</span><img src="'+esc(img)+'" alt=""><div class="row-main"><b>'+esc(p.name)+'</b><small>'+esc(p.brand)+' · '+money(p.price)+' · '+(p.stock||0)+' in stock</small></div><span class="status '+(p.status==="Active"?"live":"draft")+'">'+esc(p.status)+'</span><div class="stock-actions"><button class="stock-btn" onclick="adjustStock(\''+p.id+'\',-1)">−</button><span>'+p.stock+'</span><button class="stock-btn" onclick="adjustStock(\''+p.id+'\',1)">+</button></div><div class="row-actions"><button class="mini ghost" onclick="editProduct(\''+p.id+'\')">Edit</button><button class="mini danger" onclick="deleteProduct(\''+p.id+'\')">Delete</button></div></div>'}).join("")||'<div class="empty">No products match this filter.</div>';document.querySelectorAll(".row[draggable]").forEach(row=>{row.ondragstart=()=>{draggedId=row.dataset.id;row.classList.add("dragging")};row.ondragend=()=>row.classList.remove("dragging");row.ondragover=e=>e.preventDefault();row.ondrop=async e=>{e.preventDefault();const target=row.dataset.id;if(!draggedId||draggedId===target)return;await moveProduct(draggedId,target)}})}
async function moveProduct(id,targetId){const from=products.findIndex(p=>p.id===id),to=products.findIndex(p=>p.id===targetId);if(from<0||to<0)return;const [item]=products.splice(from,1);products.splice(to,0,item);renderProducts();try{const{error}=await client.from("products").update({updated_at:new Date().toISOString()}).eq("id",item.id);if(error)throw error}catch(e){console.error(e)}}
window.adjustStock=async(id,delta)=>{const p=products.find(x=>x.id===id);if(!p)return;const stock=Math.max(0,(p.stock||0)+delta);const{error}=await client.from("products").update({stock,updated_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else{p.stock=stock;renderStats();renderProducts();renderHealth()}};
function renderHealth(){const noImages=products.filter(p=>!p.images?.length).length,missingDesc=products.filter(p=>!p.description?.trim()).length,featured=products.filter(p=>p.featured).length;$("#healthGrid").innerHTML='<div><span>Featured</span><b>'+featured+'</b><small>Products shown in featured sections.</small></div><div><span>Missing images</span><b>'+noImages+'</b><small>Products that need a product image.</small></div><div><span>Missing descriptions</span><b>'+missingDesc+'</b><small>Products with no description.</small></div>'}
function resetForm(){$("#productForm").reset();$("#productId").value="";$("#dialogTitle").textContent="Add product";$("#productStatus").value="Active";$("#productBadge").value="";$("#productCategory").value="Collection";selectedImages=[];existingImages=[];renderImagePreview();formError("")}
function openProduct(p){$("#productId").value=p?.id||"";$("#productName").value=p?.name||"";$("#productSlug").value=p?.slug||slugify(p?.name);$("#productBrand").value=p?.brand||"Nike";$("#productCategory").value=p?.category||"Collection";$("#productPrice").value=p?.price??"";$("#productStock").value=p?.stock??0;$("#productStatus").value=p?.status||"Active";$("#productBadge").value=p?.badge||"";$("#productDescription").value=p?.description||"";$("#productSizes").value=(p?.sizes||[]).join(", ");$("#productFeatured").checked=!!p?.featured;selectedImages=[];existingImages=[...(p?.images||[])];renderImagePreview();$("#dialogTitle").textContent=p?"Edit product":"Add product";formError("");$("#productDialog").showModal()}
window.editProduct=id=>openProduct(products.find(p=>p.id===id));
function renderImagePreview(){const all=existingImages.map((url,i)=>({url,existing:true,index:i})).concat(selectedImages.map((file,i)=>({url:URL.createObjectURL(file),existing:false,index:i})));$("#imagePreview").innerHTML=all.map(x=>'<div class="preview"><img src="'+esc(x.url)+'" alt=""><button type="button" onclick="'+(x.existing?"removeExistingImage("+x.index+")":"removeSelectedImage("+x.index+")")+'">×</button></div>').join("")}
window.removeExistingImage=i=>{existingImages.splice(i,1);renderImagePreview()};window.removeSelectedImage=i=>{selectedImages.splice(i,1);renderImagePreview()};
$("#productImageFiles").onchange=e=>{selectedImages.push(...Array.from(e.target.files||[]));e.target.value="";renderImagePreview()};
async function uploadImages(productId){const urls=[...existingImages];for(const file of selectedImages){const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=productId+"/"+crypto.randomUUID()+"."+ext;const{error}=await client.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;urls.push(client.storage.from("product-images").getPublicUrl(path).data.publicUrl)}return urls}
$("#productName").oninput=e=>{if(!$("#productId").value)$("#productSlug").value=slugify(e.target.value)};
$("#productForm").onsubmit=async e=>{e.preventDefault();formError("");const btn=$("#saveProductBtn");btn.disabled=true;btn.textContent="Saving…";try{const id=$("#productId").value;const base={brand:$("#productBrand").value,name:$("#productName").value.trim(),slug:slugify($("#productSlug").value||$("#productName").value),description:$("#productDescription").value.trim(),price:Number($("#productPrice").value),category:$("#productCategory").value.trim(),stock:Number($("#productStock").value),status:$("#productStatus").value,badge:$("#productBadge").value||null,featured:$("#productFeatured").checked,sizes:$("#productSizes").value.split(",").map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()};let productId=id;if(!productId){const{data,error}=await client.from("products").insert(base).select("id").single();if(error)throw error;productId=data.id}const images=await uploadImages(productId);const{error}=await client.from("products").update({...base,images}).eq("id",productId);if(error)throw error;$("#productDialog").close();await loadProducts()}catch(error){formError(error.message)}finally{btn.disabled=false;btn.textContent="Save product"}};
window.deleteProduct=async id=>{const p=products.find(x=>x.id===id);if(!confirm("Delete "+p?.name+"?"))return;const{error}=await client.from("products").delete().eq("id",id);if(error)alert(error.message);else await loadProducts()};
$("#newProductBtn").onclick=()=>{resetForm();$("#productDialog").showModal()};$("#closeDialog").onclick=()=>$("#productDialog").close();$("#cancelProduct").onclick=()=>$("#productDialog").close();$("#logoutBtn").onclick=()=>client.auth.signOut();$("#catalogSearch").oninput=renderProducts;$("#catalogFilter").onchange=renderProducts;$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";const{error}=await client.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginError").textContent=error.message};boot();