let products=[],cart=JSON.parse(localStorage.getItem("mushtba-cart")||"[]");
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("sv-SE").format(Number(n)||0)+" kr";
const config=window.MUSHTBA_SUPABASE||{},supabaseClient=window.supabase&&config.url&&config.publishableKey?window.supabase.createClient(config.url,config.publishableKey):null;
async function loadProducts(){if(!supabaseClient){products=[];render();renderCart();initProductPage();return}const{data,error}=await supabaseClient.from("products").select("*").eq("status","Active").order("featured",{ascending:false}).order("created_at",{ascending:false});if(error){console.error("MUSHTBA catalog:",error);products=[]}else products=(data||[]).map(p=>({id:p.id,slug:p.slug,brand:p.brand,name:p.name,price:Number(p.price),img:p.images?.[0]||"",images:p.images||[],sizes:p.sizes||[],stock:p.stock,badge:p.badge,featured:p.featured,description:p.description||"",category:p.category}));render();renderCart();initProductPage()}
function card(p){return '<article class="product"><a class="product-image" href="product.html?id='+encodeURIComponent(p.id)+'"><img loading="lazy" src="'+p.img+'" alt="'+p.brand+' '+p.name+'"><span class="quick">View product ↗</span></a><div class="product-info"><div class="product-brand">'+p.brand+'</div><a class="product-name" href="product.html?id='+encodeURIComponent(p.id)+'">'+p.name+'</a><div class="product-price">'+money(p.price)+'</div></div></article>'}
function render(filter="All"){const list=filter==="All"?products:products.filter(p=>p.brand===filter),grid=$("#productGrid"),featured=$("#featuredGrid");if(grid)grid.innerHTML=list.map(card).join("")||'<div class="empty">No products available.</div>';if(featured)featured.innerHTML=products.filter(p=>p.featured).slice(0,4).map(card).join("")||products.slice(0,4).map(card).join("")||'<div class="empty">No featured products yet.</div>'}
function save(){localStorage.setItem("mushtba-cart",JSON.stringify(cart));renderCart()}
function addToCart(p){if(!p)return;cart.push(p);save();openCart()}
function renderCart(){const el=$("#cartItems"),count=$("#cartCount");if(!el||!count)return;count.textContent=cart.length;if(!cart.length){el.innerHTML='<div class="empty">Your cart is empty.</div>';$("#cartTotal").textContent="0 kr";return}el.innerHTML=cart.map((p,i)=>'<div class="cart-row"><img src="'+p.img+'" alt=""><div><strong>'+p.name+'</strong><small>'+p.brand+' · '+money(p.price)+'</small><button class="remove" data-remove="'+i+'">Remove</button></div></div>').join("");$("#cartTotal").textContent=money(cart.reduce((a,p)=>a+p.price,0));document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);save()})}
function openCart(){$("#cartDrawer")?.classList.add("open");$("#overlay")?.classList.add("open");renderCart()}
function closeCart(){$("#cartDrawer")?.classList.remove("open");$("#overlay")?.classList.remove("open")}
function initProductPage(){const id=new URLSearchParams(location.search).get("id"),wrap=$("#productDetail");if(!wrap||!id)return;const p=products.find(x=>String(x.id)===String(id));if(!p){wrap.innerHTML='<div class="empty">Product not found.</div>';return}document.title=p.name+" — MUSHTBA";wrap.innerHTML='<div class="detail-media"><img src="'+p.img+'" alt="'+p.brand+' '+p.name+'"></div><div class="detail-copy"><p class="eyebrow">'+p.brand+' / '+(p.category||"COLLECTION")+'</p><h1>'+p.name+'</h1><div class="detail-price">'+money(p.price)+'</div><p class="detail-desc">'+p.description+'</p><div class="detail-meta"><span>Selected product</span><span>Easy returns</span><span>Secure checkout</span></div><div class="size-label">SELECT SIZE</div><div class="size-grid">'+(p.sizes?.length?p.sizes.map((s,i)=>'<button class="size '+(i===0?"selected":"")+'" data-size="'+s+'">'+s+'</button>').join(""):'<span class="no-size">One size</span>')+'</div><div class="detail-actions"><button class="btn btn-light" id="buyNow">Buy now <span>→</span></button><button class="btn btn-dark" id="detailAdd">Add to bag</button></div><p class="detail-note">Free shipping over 750 kr · Easy returns</p></div>';document.querySelectorAll(".size").forEach(b=>b.onclick=()=>{document.querySelectorAll(".size").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("#detailAdd").onclick=()=>addToCart(p);$("#buyNow").onclick=()=>addToCart(p)}
if($("#cartBtn"))$("#cartBtn").onclick=openCart;if($("#closeCart"))$("#closeCart").onclick=closeCart;if($("#overlay"))$("#overlay").onclick=closeCart;
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)});
document.querySelectorAll("[data-brand]").forEach(b=>b.onclick=()=>render(b.dataset.brand));
if($("#searchBtn"))$("#searchBtn").onclick=()=>{$("#searchModal").classList.add("open");$("#searchInput").focus()};if($("#closeSearch"))$("#closeSearch").onclick=()=>$("#searchModal").classList.remove("open");
if($("#searchInput"))$("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase();$("#searchResults").innerHTML=products.filter(p=>(p.name+" "+p.brand).toLowerCase().includes(q)).map(p=>'<a class="search-result" href="product.html?id='+encodeURIComponent(p.id)+'"><span>'+p.brand+'</span><b>'+p.name+" — "+money(p.price)+'</b></a>').join("")};
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeCart();$("#searchModal")?.classList.remove("open")}});
loadProducts();