const fallbackProducts=[
{id:"demo-1",brand:"Nike",name:"Dri-FIT Training Tee",price:449,img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85",description:"Lightweight training essential built for everyday movement.",sizes:["S","M","L","XL"]},
{id:"demo-2",brand:"Under Armour",name:"Tech 2.0 T-Shirt",price:399,img:"https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=900&q=85",description:"A clean performance tee with a soft, fast-drying feel.",sizes:["S","M","L","XL"]},
{id:"demo-3",brand:"Nike",name:"Air Max Essential",price:1299,img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85",description:"Everyday cushioning and unmistakable Nike styling.",sizes:["40","41","42","43","44"]},
{id:"demo-4",brand:"Under Armour",name:"Sportstyle Hoodie",price:699,img:"https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85",description:"A heavyweight-feel layer designed for warm-ups and downtime.",sizes:["S","M","L","XL"]},
{id:"demo-5",brand:"Nike",name:"Academy Training Pants",price:649,img:"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85",description:"Streamlined training pants for sessions on the move.",sizes:["S","M","L","XL"]},
{id:"demo-6",brand:"Under Armour",name:"Velocity Shorts",price:499,img:"https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=85",description:"Light, flexible shorts built for high-output training.",sizes:["S","M","L","XL"]},
{id:"demo-7",brand:"Nike",name:"BridgeWay Runner",price:1099,img:"https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=900&q=85",description:"A versatile runner for daily miles and everyday wear.",sizes:["40","41","42","43","44"]},
{id:"demo-8",brand:"Under Armour",name:"Rival Fleece Crew",price:749,img:"https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=900&q=85",description:"Soft fleece comfort with a structured athletic fit.",sizes:["S","M","L","XL"]}];
let products=[...fallbackProducts],cart=JSON.parse(localStorage.getItem("musthba-cart")||"[]");
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("sv-SE").format(n)+" kr";
const supaConfig=window.MUSTHBA_SUPABASE||{},supabaseClient=window.supabase&&supaConfig.url&&supaConfig.publishableKey?window.supabase.createClient(supaConfig.url,supaConfig.publishableKey):null;
async function loadProducts(){if(!supabaseClient){render();renderCart();initProductPage();return}const{data,error}=await supabaseClient.from("products").select("*").eq("status","Active").order("featured",{ascending:false}).order("created_at",{ascending:false});if(error||!data?.length){console.warn("MUSTHBA catalog fallback:",error?.message||"no products");render();renderCart();initProductPage();return}products=data.map(p=>({id:p.id,brand:p.brand,name:p.name,price:Number(p.price),img:p.images?.[0]||"",images:p.images||[],sizes:p.sizes||[],stock:p.stock,badge:p.badge,featured:p.featured,description:p.description||"Performance-focused essentials selected by MUSTHBA.",category:p.category}));render();renderCart();initProductPage()}
function card(p){return '<article class="product"><a class="product-image" href="product.html?id='+encodeURIComponent(p.id)+'"><img loading="lazy" src="'+p.img+'" alt="'+p.brand+' '+p.name+'"><span class="quick">View product ↗</span></a><div class="product-info"><div class="product-brand">'+p.brand+'</div><a class="product-name" href="product.html?id='+encodeURIComponent(p.id)+'">'+p.name+'</a><div class="product-price">'+money(p.price)+'</div></div></article>'}
function render(filter="All"){const list=filter==="All"?products:products.filter(p=>p.brand===filter),grid=$("#productGrid"),featured=$("#featuredGrid");if(grid)grid.innerHTML=list.map(card).join("");if(featured)featured.innerHTML=products.filter(p=>p.featured).slice(0,4).map(card).join("")||products.slice(0,4).map(card).join("")}
function save(){localStorage.setItem("musthba-cart",JSON.stringify(cart));renderCart()}
function addToCart(p){if(!p)return;cart.push(p);save();openCart()}
function renderCart(){const el=$("#cartItems"),count=$("#cartCount");if(!el||!count)return;count.textContent=cart.length;if(!cart.length){el.innerHTML='<div class="empty">Your cart is empty.</div>';$("#cartTotal").textContent="0 kr";return}el.innerHTML=cart.map((p,i)=>'<div class="cart-row"><img src="'+p.img+'" alt=""><div><strong>'+p.name+'</strong><small>'+p.brand+' · '+money(p.price)+'</small><button class="remove" data-remove="'+i+'">Remove</button></div></div>').join("");$("#cartTotal").textContent=money(cart.reduce((a,p)=>a+p.price,0));document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);save()})}
function openCart(){$("#cartDrawer")?.classList.add("open");$("#overlay")?.classList.add("open");renderCart()}
function closeCart(){$("#cartDrawer")?.classList.remove("open");$("#overlay")?.classList.remove("open")}
function initProductPage(){const id=new URLSearchParams(location.search).get("id"),wrap=$("#productDetail");if(!wrap||!id)return;const p=products.find(x=>String(x.id)===String(id));if(!p){wrap.innerHTML='<div class="empty">Product not found.</div>';return}document.title=p.name+" — MUSTHBA";wrap.innerHTML='<div class="detail-media"><img src="'+p.img+'" alt="'+p.brand+' '+p.name+'"></div><div class="detail-copy"><p class="eyebrow">'+p.brand+' / '+(p.category||"COLLECTION")+'</p><h1>'+p.name+'</h1><div class="detail-price">'+money(p.price)+'</div><p class="detail-desc">'+(p.description||"Performance-focused essentials selected by MUSTHBA.")+'</p><div class="detail-meta"><span>Premium selection</span><span>Easy returns</span><span>Secure checkout</span></div><div class="size-label">SELECT SIZE</div><div class="size-grid">'+(p.sizes?.length?p.sizes.map((s,i)=>'<button class="size '+(i===0?"selected":"")+'" data-size="'+s+'">'+s+'</button>').join(""):'<span class="no-size">One size</span>')+'</div><div class="detail-actions"><button class="btn btn-light" id="buyNow">Buy now <span>→</span></button><button class="btn btn-dark" id="detailAdd">Add to bag</button></div><p class="detail-note">Free shipping over 750 kr · Easy returns</p></div>';document.querySelectorAll(".size").forEach(b=>b.onclick=()=>{document.querySelectorAll(".size").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("#detailAdd").onclick=()=>addToCart(p);$("#buyNow").onclick=()=>addToCart(p)}
if($("#cartBtn"))$("#cartBtn").onclick=openCart;if($("#closeCart"))$("#closeCart").onclick=closeCart;if($("#overlay"))$("#overlay").onclick=closeCart;
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)});
document.querySelectorAll("[data-brand]").forEach(b=>b.onclick=()=>render(b.dataset.brand));
if($("#searchBtn"))$("#searchBtn").onclick=()=>{$("#searchModal").classList.add("open");$("#searchInput").focus()};if($("#closeSearch"))$("#closeSearch").onclick=()=>$("#searchModal").classList.remove("open");
if($("#searchInput"))$("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase();$("#searchResults").innerHTML=products.filter(p=>(p.name+" "+p.brand).toLowerCase().includes(q)).map(p=>'<a class="search-result" href="product.html?id='+encodeURIComponent(p.id)+'"><span>'+p.brand+'</span><b>'+p.name+" — "+money(p.price)+'</b></a>').join("")};
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeCart();$("#searchModal")?.classList.remove("open")}});
loadProducts();